# Generated by Django 2.1.15 on 2013-11-07 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='asdf', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='asdf', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='asdf', max_length=101),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='readtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
